set FUSE subtype and fsname by default
cryptomator/cli pull request #39
Opened 2020-11-08 21:03 UTC by mhogomchungu

Currently, a mounted cryptomator volume shows up in "/proc/self/mountinfo" in linux as follows:

```
41 33 0:34 / /home/_/cryptomator rw,nosuid,nodev,relatime - fuse.fusefs-1001772408 fusefs-1001772408 rw,user_id=500,group_id=500

```

Notice that there is no way of knowing if this entry belongs to cryptomator because "fuse.fusefs-1001772408" is not very meaningful because the numbers are randomly generated i think from here[1]

With this patch, the above line shows up as below
```
49 33 0:42 / /home/ink/bbb rw,nosuid,nodev,relatime - fuse.cryptomator cryptomator@/home/ink/.vaults/cryptomator rw,user_id=500,group_id=500
```
The above line has the following improvements :-
1. The path to the vault is displayed.
2. The file system entry has the correct entry of "fuse.cryptomator".
3. The path to the vault starts with "cryptomator@". This is the standard way of identifying FUSE mounts that do not set the file system type.

The last two makes it easy to identify cryptomator volumes and are necessary for identification by other tools like file managers and desktop environments.

[1] https://github.com/SerCeMan/jnr-fuse/blob/c5d071af150a191c72b6ed91fd5865ffa1853d4a/src/main/java/ru/serce/jnrfuse/AbstractFuseFS.java#L315

2020-11-08 21:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cryptomator/cli?pullRequest=39) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cryptomator/cli?pullRequest=39) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cryptomator/cli?pullRequest=39) it.</sub>

2020-11-09 00:39 UTC, mhogomchungu commented
The second commit leaves the defaults as they are and it allows users to set FUSE fsname and subtype if they want to and an ideal command that uses them looks like below

```
cryptomator-cli --vault blabla=/path/to/cryptomator -fusemount blabla=/path/to/mountpath -fsname blabla=cryptomator@/path/to/cryptomator -subtype blabla=cryptomator

```

2020-11-19 12:29 UTC, tobihagemann commented
Thank you for your PR! I must admit, I think it would be much easier if we'd introduce a `mountFlags` option and not options for each mount flag (because the list could become very long then). What do you think?

2020-11-19 14:00 UTC, mhogomchungu commented
That makes sense and the latest code has the option.

Example is below where it sets fsname,subtype and allow_other. 

With an option like fsname that takes an argument, the option is supposed to be in a format of ```fsname=cryptomator``` but i went with ```fsname cryptomator``` because the command line parser seems to be confused when it sees the "=" sign.

```
java -jar cryptomator-cli.jar --vault aaa=cipherPath -fusemount aaa=mountPath -mountFlags aaa=fsname cryptomator,subtype cryptomater,allow_other
```

2020-11-20 00:00 UTC, tobihagemann commented on src/main/java/org/cryptomator/cli/frontend/FuseMount.java
> +	private Path vaultPath;
I think the `vaultPath` is not used anymore, could be deleted? (Also in the constructor below.)

2020-11-20 00:08 UTC, tobihagemann commented
Out of curiosity, does the command-line parser handle quotes better? Would something like this be possible (without making things more complex)?

```
-mountFlags aaa="-ofsname=cryptomator -osubtype=cryptomater -oallow_other"
```

And then not even adding them to the default flags but using them "as is".

2020-11-20 03:57 UTC, mhogomchungu commented
> Out of curiosity, does the command-line parser handle quotes better? Would something like this be possible (without making things more complex)?

No, it does not, it stops when it sees the "=" sign.

```
java -jar cryptomator-cli.jar --vault aaa=cipherPath -fusemount aaa=aaa -mountFlags aaa="-ofsname=cryptomator -osubtype=cryptomater -oallow_other"
06:54:30.399 [main] INFO  org.cryptomator.cli.CryptomatorCli - Unlocking vault "aaa" located at /home/ink/.vaults/cryptomator
06:54:30.411 [main] INFO  o.c.c.p.PasswordFromStdInputStrategy - Vault 'aaa' password from standard input.
Enter password for vault 'aaa': 

fuse: unknown option `-ofsname'
06:54:34.679 [main] ERROR o.cryptomator.cli.frontend.FuseMount - Can't mount: aaa, error: ru.serce.jnrfuse.FuseException: Unable to mount FS
06:54:34.683 [main] INFO  org.cryptomator.cli.CryptomatorCli - Press Ctrl+C to terminate.

```

2020-11-20 07:43 UTC, mhogomchungu commented
"=" character appears to be an illegal character and any option including cipher path and mount point path that has it will be broken because it will get truncated at the location of the character.

2021-12-16 20:09 UTC, overheadhunter requested changes
Can you add documentation to `README.md`? Then we could release this with 0.5.0

2024-09-04 15:24 UTC, infeo commented
We will rewrite the project in a different framework, hence this PR is obsolete.

2024-09-04 15:24 UTC, closed without merging