This pull request updates both cryptomator dependancies to the latest version (as of Jun '23)
cryptomator/cli pull request #56
Opened 2023-07-17 17:22 UTC by greycubesgav

This pull request is a very rough update to bump the versions of dependancies cryptofs (v2.3.1 -> 2.6.5) and webdav-nio (v1.2.6 -> 2.0.3) to the latest versions.

I'm not a java expert so this is more a proof of concept pull request to attempt to drive interaction from the cryptomator team to release a new version of cryptomator cli with the latest versions. **These changes has not been fully tested, but will allow existing files in a vault to be browsed and new file written through webdav.**

* The 1st bump of cryptofs to 2.6.5 only required some dependancy version locking in the pom file.
* The 2nd bump of webdav-nio to 2.0.3 required some code changes to cryptomator/cli/frontend/WebDav.java due to this code change in webdav-nio: https://github.com/cryptomator/webdav-nio-adapter/pull/44/commits/1b86572b7a4713ab9fd0159004560b5e19afd0db

2023-07-17 17:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cryptomator/cli?pullRequest=56) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cryptomator/cli?pullRequest=56) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cryptomator/cli?pullRequest=56) it.</sub>

2023-07-18 11:35 UTC, overheadhunter requested changes
What is the purpose of the added dependencies? I believe you can remove them.

2023-07-20 14:32 UTC, greycubesgav commented
You're right, thanks for taking a look.
They were added when bumping just cryptofs.version to 2.6.5, now both dependancies are updated they are no longer needed.
New commit attached.

2023-07-20 19:54 UTC, overheadhunter approved these changes

2023-07-24 09:47 UTC, merged